#!/usr/bin/env python3
"""summary.py — the imperative shell (PROVIDED, complete).

You do not edit this file. It is here so you can see the other half of the
design: the thin shell that does all the I/O and none of the logic. Once
you finish the three exercises in summary_core.py, this shell will run the
whole tool by calling your pure functions.

    echo "1 2 3 4 5" | python3 starter/summary.py
    python3 starter/summary.py numbers.txt
"""
import sys

import summary_core


def read_input(argv):
    """Return the raw text to summarize: from a named file, or from stdin.

    Lives in the shell, not the core, because it performs I/O.
    """
    if len(argv) > 1:
        with open(argv[1], "r", encoding="utf-8") as handle:
            return handle.read()
    return sys.stdin.read()


def main(argv):
    """Read input, run the pure core, print the result, choose the exit code."""
    try:
        text = read_input(argv)
        numbers = summary_core.parse_numbers(text)
        summary = summary_core.summarize(numbers)
    except (ValueError, OSError) as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
    print(summary_core.format_summary(summary))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
